# Board-specific CPU and hard-float flags are selected in meson.build.
[binaries]
c = 'arm-none-eabi-gcc'
cpp = 'arm-none-eabi-g++'
ar = 'arm-none-eabi-ar'
strip = 'arm-none-eabi-strip'
objcopy = 'arm-none-eabi-objcopy'
nm = 'arm-none-eabi-nm'
objdump = 'arm-none-eabi-objdump'

[host_machine]
system = 'baremetal'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
c_std = 'gnu11'
